name: openpower-agent-stack

services:
  browser-automation:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DISPLAY=:99
    volumes:
      - ./src:/app/src
      - model-cache:/app/models
    depends_on:
      - model-runner
      - mcp-server

  model-runner:
    image: docker/dev-environments-default:stable
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    volumes:
      - model-cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  mcp-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.mcp
    ports:
      - "8081:8081"
    volumes:
      - ./tools:/app/tools
    environment:
      - MCP_SERVER_PORT=8081
      - MODEL_RUNNER_URL=http://model-runner:8080

  sequential-thinking:
    image: mcp/sequentialthinking
    ports:
      - "8082:8080"
    environment:
      - MCP_SERVER_PORT=8080
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/.well-known/mcp.json"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  model-cache:

x-models:
  llm:
    context_size: 4096
    models:
      smollm2:
        source: ai/smollm2:360M-Q4_K_M
        config:
          temperature: 0.7
          top_p: 0.9
      smollm3:
        source: ai/smollm3
        config:
          temperature: 0.8
          top_k: 40
          
x-mcp-tools:
  browser-automation:
    type: "sse"
    url: "http://browser-automation:8080/sse"
  web-search:
    type: "rest"
    url: "http://mcp-server:8081/tools/web-search"
  file-operations:
    type: "rest"
    url: "http://mcp-server:8081/tools/files"
  sequential-thinking:
    type: "rest"
    url: "http://sequential-thinking:8080/tools/sequentialthinking"
    config:
      verify_signature: true
      cosign_key: "https://raw.githubusercontent.com/docker/keyring/refs/heads/main/public/mcp/latest.pub"
